### ISSUE TITLE
Send Methods

### ISSUE THREAD

**Issue by lillebutik** [onesteinbv/addons-sendcloud#1]
It is very common that a Shop does not offer the customers all the possible send methods offered by Sendcloud.

I would suggest that you import the Send methods into Odoo and allow the backend user to only publish only the relevant ones. 

You also want to allow some filtering based on country in backend. 
That would also be the right spot to handle multiple websites :)

**Comment by PatrickMallee** [comment]
Hi Littebutik,

Please check the shipping methods under inventory/configuration/shipping methods. In the shipping method you can choose if you want to publish this method on your website and select designation availability. Hope this helps.
