### ISSUE TITLE
[14.0] no e-mail in delivery address causes error on validating stock.picking

### ISSUE THREAD

**Issue by janbec** [onesteinbv/addons-sendcloud#10]
## Current behavior
When the customer chooses to have a different delivery address, by default odoo does not ask for an email address. When validating the stock.picking to the delivery address, the connector will produce an error:
![grafik](https://user-images.githubusercontent.com/28890800/146554356-b3415d61-f832-4e20-8470-d257ae117f8c.png)

## Desired Behavior
This can be easily resolved by copying the email from the main contact to the delivery address, but it would be nice to have an automatic fallback for these kind of situations, something like:
```
 if sender.email:
            vals.update({"email": sender.email})
 if not sender.email:
            vals.update({"email": sender.parent_id.email})
```

See [here](https://github.com/onesteinbv/addons-sendcloud/blob/79b6e025db6a1e7f578a01799207a0a5c47016e6/delivery_sendcloud_official/models/stock_picking.py#L148).

**Comment by tarteo** [comment]
Thanks! Fixed this for 14.0 guess this is also the case for 15.0
