### ISSUE TITLE
[14.0] street name without emtpy space between street and house number causes error on delivery validation

### ISSUE THREAD

**Issue by janbec** [onesteinbv/addons-sendcloud#11]
## Current behavior
When a customer enters his streetname and housenumber without an empty space between street and housenumber, the following error will occur:
![grafik](https://user-images.githubusercontent.com/28890800/146554954-a05bbb1d-f55e-4f98-bc84-430fbddfb321.png)

If we change the address from e.g. Musterstr.1 to Musterstr. 1, the delivery will go through without any error.

**Comment by tarteo** [comment]
@janbec Thanks, should be fixed for 14.0 now

**Comment by janbec** [comment]
Thanks for fixing this @tarteo 🥇
