### ISSUE TITLE
Error Whene Select  Sendcloud UPS to Access Point Economy 7-10kg

### ISSUE THREAD

**Issue by mboujdid** [onesteinbv/addons-sendcloud#16]
Hello,

I use Odoo 13 EE

You have any idea about this error:
- I select   carrier Sendcloud UPS to Access Point error "Cannot set properties of undefined (setting 'carrier_selection')" displayed
- There is no error for other carrier witout Access point!

![Err](https://user-images.githubusercontent.com/6718688/162624563-86dcab47-905a-4846-8fdf-062b8aa926a4.png)

Thanks

**Comment by mboujdid** [comment]
Hi @all,

I find the problem origin!

**To reproduce the error just:**

- Disable payment methods
- Click on a Sendcloud UPS to Access Point Economy"


You must fix javascript code  website_sendcloud_official/static/src/js/frontend.js !

Thanks

**Comment by tarteo** [comment]
Thanks for reporting I'll will make a fix ASAP!

**Comment by tarteo** [comment]
@mboujdid  I'm able to reproduce this error when i turn off all the payment acquirers. But why would you want no payment acquirers (not even wire transfers)?
