### ISSUE TITLE
Issue with country of origin - Odoo Enterprise

### ISSUE THREAD

**Issue by HunkBenny** [onesteinbv/addons-sendcloud#18]
For shipping outside of the EEA, [you advise users to use the 'product_harmonized_system' module from OCA](https://github.com/onesteinbv/addons-sendcloud/blob/15.0/delivery_sendcloud_official/README.rst#id15). However, [this module is incompatible with Odoo Enterprise.](https://odoo-community.org/shop/product-harmonized-system-codes-1938#id1). So; your Sendcloud-app will not behave as expected for Odoo Enterprise.

Look at lines 333 - 340:
https://github.com/onesteinbv/addons-sendcloud/blob/b67059c317a7700da7a4838e9ec90572a25947b3/delivery_sendcloud_official/models/stock_picking.py#L328-L341

For Odoo Enterprise, if the 'account_intrastat' module is enabled, a country_of_origin field is added to products that has the functionality that's needed. The value can be accessed as follows:

`
origin_country = product_tmplate.intrastat_origin_country_id.code
`
I hardcoded this in our backend for now. It works for us.

What I advise is adding something along the lines of:
```
is_account_intrastat_installed = self.env["ir.module.module"].search([
            ("name", "=", "account_intrastat "),
            ("state", "=", "installed")
        ], limit=1)
if is_account_intrastat_installed:
    origin_country = product_tmplate.intrastat_origin_country_id.code
```

Love to hear from ya!

Benny

**Comment by astirpe** [comment]
Hi @HunkBenny thank you very much! That's very appreciated. I'm going to apply your solution soon!

**Comment by astirpe** [comment]
@HunkBenny the module was updated with the fix you  proposed. Thanks again!
