### ISSUE TITLE
Invoicing delivery charges

### ISSUE THREAD

**Issue by lillebutik** [onesteinbv/addons-sendcloud#2]
<img width="1129" alt="Bildschirmfoto 2021-04-13 um 23 59 26" src="https://user-images.githubusercontent.com/48350476/114626725-66f04200-9cb4-11eb-9787-d35877867dfd.png">

1) Create Order in Website
2) Confirm Order in Backend
3) Pick ordered Products
4) Validate Picking -> Parcel is created and Label can be printed in Sendcloud.
5) Create invoice [Shipping costs are not marked as delivered and a missing on the invoice]

Im sure the issue is between the chair and the keyboard. What have I forgotten in the configuration?

**Comment by PatrickMallee** [comment]
Hi lillebutik,

I've tried to reproduce the issue but I don't get the same results. The only thing I can think of is that the delivery product is changed. In our environment the "can be sold" and "can be purchased" are not checked. 
![product1](https://user-images.githubusercontent.com/39047219/114664663-4e0b7f00-9cfc-11eb-8eff-086ad0534206.png)

If you have checked the "can be sold" option make sure that you set the invoicing policy to ordered quantities
![product2](https://user-images.githubusercontent.com/39047219/114664984-c114f580-9cfc-11eb-8d94-cd9a37d91eff.png)
Also make sure that producttype is set to "service". 

Please let me know if this solves the issue.

**Comment by lillebutik** [comment]
I can longer reproduce the issue myself. I think it was because the integration was not 100% complete when I discovered the issue. Your idea was also my first thought.
