### ISSUE TITLE
KIT product price not correct

### ISSUE THREAD

**Issue by vandekul** [onesteinbv/addons-sendcloud#20]
I have configured a product as a KIT and although it takes the different components (also products), the price it indicates is not correct in Parcel Items, what it reports is the total price of sale line product.

On the other hand, it does not take the HS Code of the product (each component) either.

**Comment by Jan-Onestein** [comment]
Thank you for reaching out to us  @vandekul 
Can you please provide some additional info like which version you are using?

Thanks in advance !!!

**Comment by vandekul** [comment]
Hi! I'm using odoo 16.0 and also module in 16.0 version.

In order to clarify. I have a product, that has it's BoM as a KIT, each sub-product of the KIT has its price and its HS, but also the main product has its own price and its HS, what the module doesn't do is take the price of each sub-product, it takes the price of the product.

Example:
Product 1 (main product): 

- Price 30€ 
- HS 12345678 
- BOM (type = KIT):
-- Subproduct 1: Price 15€ HS 1111
-- Subproduct 2: Price 15€ HS 2222
-- Subproduct 3: Price 10€ HS 3333

What does the module is send the items of the subproduct with the price and HS of the main product:
Subproduct 1  - Price 30€ - HS 12345678
Subproduct 2  - Price 30€ - HS 12345678 
Subproduct 3 - Price 30 € - HS 12345678

What expeted:
**First option:**  items with its HS number of the product and proporcional part of the price
Subproduct 1: Price ((15/40)*30) = 11,25€ HS 1111
Subproduct 2: Price ((15/40)*30) = 11,25€ HS 2222
Subproduct 3: Price ((10/40)*30) = 7,5€ HS 3333

**Second option:** possibility of send only the main product and not the components of the KIT
Product 1: Price 30€ HS 12345678

Hope it helps and clarify.

**Comment by vandekul** [comment]
Hello, I made some modifications so that the module worked as I needed.

I leave it here in case you think it may be useful.

https://github.com/vandekul/delivery_sendcloud_official

Regards

**Comment by Jan-Onestein** [comment]
Thank you very much for the update !!!
Our developers will have a look at it and make the needed adjustments at our side

**Comment by fumanshu007** [comment]
@vandekul : can you send me your email address? We have an update on this, that can be tested. With regards Randy Charleston > r.charleston@onestein.nl
