### ISSUE TITLE
Shipping labels order the delivery order

### ISSUE THREAD

**Issue by lillebutik** [onesteinbv/addons-sendcloud#3]
Would it make sense to store the shipping label(s) where they are normally stored?

<img width="1143" alt="Bildschirmfoto 2021-04-14 um 15 49 02" src="https://user-images.githubusercontent.com/48350476/114721371-25ee4100-9d39-11eb-937a-ba99b35c5200.png">

We are using direct printing from VentorTech.

**Comment by PatrickMallee** [comment]
We have made a separate module for this since this only works when you're use the direct print / printnode module from Ventortech. We will publish this within a couple of days. I will let you know when it's published

**Comment by astirpe** [comment]
Hi @lillebutik, the module `delivery_sendcloud_official_printnode` is published and available for [V13](https://github.com/onesteinbv/addons-sendcloud/tree/13.0) and [V14](https://github.com/onesteinbv/addons-sendcloud/tree/14.0).
