### ISSUE TITLE
Changes to Deliver.Carrier country_ids are deleted by Sendcloud

### ISSUE THREAD

**Issue by lillebutik** [onesteinbv/addons-sendcloud#6]
1. Edit the field
<img width="587" alt="Bildschirmfoto 2021-10-28 um 10 26 17" src="https://user-images.githubusercontent.com/48350476/139217296-a0a6debc-4d19-455b-bdfe-de8c1c8f600b.png">

2. Wait until the auto sync with Sendcloud has run.

3. The changes you made are gone.

It is an issue because free shipping really depends on 2 parameters 1. Shipping Costs and 2. The ordered amount.

**Comment by tarteo** [comment]
@lillebutik Thanks, at which point do you want to change the countries provided by Sendcloud? What is the reason. Is this only the case for free shipping?

**Comment by lillebutik** [comment]
The shipping fees vary from something like 4€ to 58€ per parcel. So it really important that we offer free shipping not only based on the order amount but also the shipping cost (country). 

What we have been doing is creating multiple shipping methods and then restricting the countries where a given shipping method is available to countries with similar shipping fees.

What im looking into at the moment is using Promotions / Coupons to trigger free shipping. That might very well turn out to be the best and cleanest way to handle the use case.

**Comment by tarteo** [comment]
@lillebutik Clear, I'll create a checkbox "Don't sync with Sendcloud", which prevents the countries from being overriden by the Sendcloud synchronization.

**Comment by tarteo** [comment]
I've updated the code with this new field.
![image](https://user-images.githubusercontent.com/10028499/140293999-5b2318c5-e127-4e3e-aa11-f855db5a5391.png)
