### ISSUE TITLE
please upload V15 migration of "delivery_sendcloud_official_printnode" module part

### ISSUE THREAD

**Issue by LaurinCoder** [onesteinbv/addons-sendcloud#7]
can you please upload V15 migration of "delivery_sendcloud_official_printnode" module part

and can you please also update version of it on apps.odoo.com so I can licence it?
Thank you!

**Comment by tarteo** [comment]
Here it is: https://apps.odoo.com/apps/modules/15.0/delivery_sendcloud_official_printnode/
