### ISSUE TITLE
[14.0] parcel_item_ids uses description_picking as parcel_item name (no variant values)

### ISSUE THREAD

**Issue by janbec** [onesteinbv/addons-sendcloud#9]
## Current behavior
When preparing the values for the parcel line, the stock.move field description_picking is used:

```
# Parcel items (mandatory)
        line_vals = {
            "description": move.description_picking or move.name,
            "quantity": int(move.product_uom_qty),  # TODO should be quantity_done ?
            "weight": weight,
            "value": move.sale_line_id.price_unit,
            # not converted to euro as the currency is always set
        }
```
 Taken from [here](https://github.com/onesteinbv/addons-sendcloud/blob/79b6e025db6a1e7f578a01799207a0a5c47016e6/delivery_sendcloud_official/models/stock_picking.py#L272).

## Problem
The field description_picking describes the product.template, not the product.product. We have an order with a glass in four different colors. Since only the name of the product.template is passed to sendcloud, the customer can't tell the glasses apart in the return portal. There are 4 lines with the same name.

## Suggestion
What do you think about replacing `move.description_picking` with `move.product_id` ?

**Comment by tarteo** [comment]
We can also use `move.name`. This includes the sales description of the product (`description_sale`)

![image](https://user-images.githubusercontent.com/10028499/148217985-3388c402-18c2-4b76-90a0-badc5fc3c128.png)

What do you think is best? @janbec @PatrickMallee

**Comment by janbec** [comment]
@tarteo 
I tend towards using product_id but for us both solutions would be fine.
Surely, the customer might have some more information on identifying the right product for the return but on the other hand it might bloat up the product selection for the return if you have really long description_sale.

**Comment by tarteo** [comment]
True, `product_id` it will be :+1:

**Comment by janbec** [comment]
Hey @tarteo 
thanks for taking care of the issues I reported 👍🏻 !!

We are using the API integration. I had an error when trying with odoo. I am curious, are you using API or odoo for your testing purposes?

**Comment by tarteo** [comment]
@janbec No problem thanks for reporting the issues. I use Odoo integration with https://ngrok.com/ to test.

**Comment by janbec** [comment]
@tarteo Will take a look at it
On our production system, I always get the following error:
```
Error while checking the webhook connection.
Webhook URL: METHOD NOT ALLOWED (error code 405)
```
Since API worked, I didn't really looked into it. Not sure, is there a difference between the two integrations?
